### ISSUE TITLE
How to process the Tmall dataset？

### ISSUE THREAD

**Issue by Amelia0312** [akaxlh/GNMR#1]
How to process the Tmall dataset？

**Comment by nishawn** [comment]
Thank you for reading!
I am wondering if you could kindly send me the pretrain/PreTrnEmbed_usr/itm that used in labcode_preSamp.py(with graph sampling) and the necessary information about it. I promise they will be used only for research purposed.
Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by akaxlh** [comment]
To predict purchase behavior, it only requires the labcode.py. The pretrained embeddings are used for overall prediction for Taobao data, which is not included in our paper. Though I will upload the pretrained embeddings later.
